<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="MOtionControlEXT" Id="{2cd156df-35e5-41ef-8fc5-c19aca351a71}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC MOtionControlEXT EXTENDS MotionControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>