<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.3">
  <POU Name="GET_OPCUA_SERVER_URL" Id="{8e0d3ee6-ea21-480b-8068-0b041dccf82e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION GET_OPCUA_SERVER_URL : STRING(255)
VAR_INPUT
	HOSTNAME 	: STRING(255);
	PORT 		: UDINT;
END_VAR
VAR
	//opc.tcp://192.168.254.2:4840
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GET_BECKHOFF_OPCUA_NAMESPACE := CONCAT('opc.tcp://', CONCAT(HOSTNAME, CONCAT(':',UDINT_TO_STRING(PORT))));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>