<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="NCITable" Id="{4a7feab4-ad5e-44ea-b084-0a84be7b3292}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK NCITable
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	nciTable : ST_NciFeedGroupTable;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>